### ISSUE TITLE
Make "See for yourself" look clickable

### ISSUE THREAD

**Issue by pmarsceill** [orientation/orientation.io#2]
I struggled to find the link to view a demo on this page because there was no button or text that looked clickable.

![screen shot 2016-01-27 at 3 41 53 pm](https://cloud.githubusercontent.com/assets/896475/12627564/85c9d73e-c50c-11e5-8591-ae534c4d940b.png)

**Comment by olivierlacan** [comment]
<img width="746" alt="screen shot 2016-01-27 at 4 12 07 pm" src="https://cloud.githubusercontent.com/assets/65950/12628351/bc3b7544-c510-11e5-8bbf-a8653bfb1287.png">

Prototype.

**Comment by olivierlacan** [comment]
Also, get a Retina screen you hippie.

**Comment by pmarsceill** [comment]
> Prototype.

Cool. Probably could use `#4cadbf` as the bg color since that is what you were using as the old hover state.

**Comment by pmarsceill** [comment]
Fixed
